function [fitresult, gof] = createFit_compliance(sD, compliance)
%CREATEFIT(SD,COMPLIANCE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : sD
%      Y Output: compliance
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Mar-2016 10:52:06


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( sD, compliance );

% Set up fittype and options.
ft = fittype( 'a*exp(-x)+ b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [0.335356839962797 0.679727951377338];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'compliance vs. sD', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'sD' );
ylabel( 'compliance' );
grid on


