function [ft,gofR2,figure_handle] = createFit_viscoelastic2D(x, y, N,show_figure_number);
%CREATEFIT(FORCE,DISTANCE)
%  Create a fit.
%
%  Data for 'viscoelastic_2D' fit:
%      X Input : force
%      Y Output: distance
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Dec-2015 14:28:34


%% Fit: 'viscoelastic_2D'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'a*x^1.5+b*x+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf];
opts.Robust = 'Bisquare';
opts.StartPoint = [0.0344460805029088 0.438744359656398 0.381558457093008];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[ft, gof] = fit( xData, yData, ft, opts );
gofR2=gof.rsquare;


figure_handle=0;
if nargin>=4
% Plot fit with data.
figure_handle=figure(show_figure_number);
plot( ft, xData, yData,'.-' );
% legend( h, 'y vs. x')
% Label axes
xlabel( 'x' );
ylabel( 'y' );
grid on
end


