function [fitresult, gof] = createFit_interpolate(distance, force)
%CREATEFIT(DISTANCE_1,FORCE_1)
%  Create a fit.
%
%  Data for 'linearinterpolant' fit:
%      X Input : distance_1
%      Y Output: force_1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Dec-2015 19:48:00


%% Fit: 'linearinterpolant'.
[xData, yData] = prepareCurveData( distance, force );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( ft );
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'linearinterpolant' );
h = plot( fitresult, xData, yData );
legend( h, 'force_1 vs. distance_1', 'linearinterpolant', 'Location', 'NorthEast' );
% Label axes
xlabel( 'distance_1' );
ylabel( 'force_1' );
grid on


