function [fitresult, gof] = createFit_gaussian(distance, force)
%CREATEFIT(DISTANCE_1,FORCE_1)
%  Create a fit.
%
%  Data for 'gaussianfit' fit:
%      X Input : distance_1
%      Y Output: force_1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Dec-2015 00:27:16


%% Fit: 'gaussianfit'.
[xData, yData] = prepareCurveData( distance, force );

% Set up fittype and options.
ft = fittype( 'gauss2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [0.516576683035021 324.1499 26.7609285407136 0.307875480022422 275.0418 29.37297876141];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'gaussianfit' );
h = plot( fitresult, xData, yData );
legend( h, 'force_1 vs. distance_1', 'gaussianfit', 'Location', 'NorthEast' );
% Label axes
xlabel distance_1
ylabel force_1
grid on


