function [fitresult, gof] = createFit_expotential(sDisplacement, sForce)
%CREATEFIT(SDISPLACEMENT,SFORCE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : sDisplacement
%      Y Output: sForce
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Mar-2016 13:19:22


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( sDisplacement, sForce );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [5.25061797862413e+17 0.00759988985270382];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'sForce vs. sDisplacement', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'sDisplacement' );
ylabel( 'sForce' );
grid on


